"""Public-domain Indian paintings for each beat: Wikimedia Commons first, then Cleveland Museum of Art (CC0).

Only paintings, prints, miniatures and manuscript folios pass; photographs, idols, modern works and anything
tagged as AI-generated are refused, so no AI-made deity face can reach a Short.
"""

from __future__ import annotations

import html
import io
import logging
import re
import time
from pathlib import Path

import requests

log = logging.getLogger(__name__)

USER_AGENT = "MoolKathaLite/1.0 (https://www.youtube.com/@moolkatha; educational, public-domain art)"
COMMONS_API = "https://commons.wikimedia.org/w/api.php"
CLEVELAND_API = "https://openaccess-api.clevelandart.org/api/artworks/"
MIN_SIDE = 1000
THUMB_STEPS = (960, 1280, 1920)
# Share-alike, non-commercial and no-derivative licences are excluded.
LICENSE_OK = re.compile(r"^(public domain|pd\b|pd-|cc0|cc by \d(\.\d)?( [a-z]{2})?$|cc-by-\d(\.\d)?(-[a-z]{2})?$)", re.I)
PAINTING = re.compile(
    r"painting|miniature|ravi varma|dhurandhar|pahari|kangra|basohli|guler|chamba|mughal|razmnama|folio|manuscript|"
    r"rajput|rajasthani|mewar|bundi|kota|jaipur|kishangarh|kalighat|bazaar art|chromolithograph|lithograph|"
    r"oleograph|watercolou?r|gouache|tempera|ramayana|mahabharata|bhagavata|gita govinda|harivamsa|illustrat",
    re.I)
REJECT = re.compile(
    r"photograph|\bphoto\b|statue|sculpture|\bidol\b|murti|temple|relief|carving|bronze|ai[- ]generated|"
    r"artificial intelligence|stable diffusion|midjourney|dall-?e|generated by|screenshot|\bfilm\b|movie|actor|"
    r"\btv\b|television|serial|poster|festival|procession|pandal|stamp|coin|banknote|\bmap\b|logo|diagram|"
    r"tattoo|costume|cosplay|ramlila|ram leela|kathakali|dance|performance",
    re.I)
WORK_FALLBACKS = {
    "ramayana": ["Ramayana painting", "Raja Ravi Varma Rama", "Ramayana folio"],
    "mahabharata": ["Razmnama", "Mahabharata painting", "Ravi Varma Mahabharata"],
    "gita": ["Krishna Arjuna chariot painting", "Bhagavad Gita painting", "Razmnama Krishna"],
    "vishnu_purana": ["Vishnu painting", "Bhagavata Purana folio", "Krishna painting Pahari"],
}
_TAG = re.compile(r"<[^>]+>")


def _get(url: str, params: dict) -> dict:
    for attempt in range(4):
        try:
            resp = requests.get(url, params=params, headers={"User-Agent": USER_AGENT}, timeout=45)
            if resp.status_code == 200:
                return resp.json()
            if resp.status_code not in (429, 500, 502, 503, 504):
                resp.raise_for_status()
        except (requests.RequestException, ValueError) as err:
            if attempt == 3:
                raise
            log.info("art search retry after %s", err)
        time.sleep(3 * (attempt + 1))
    raise RuntimeError(f"{url} kept failing")


def _plain(value: str | None) -> str:
    return " ".join(html.unescape(_TAG.sub(" ", value or "")).split())


def _meta(meta: dict, key: str) -> str:
    return _plain((meta.get(key) or {}).get("value"))


def _year(text: str) -> int | None:
    years = [int(y) for y in re.findall(r"\b(1[0-9]{3}|20[0-9]{2})\b", text)]
    return min(years) if years else None


def thumb_url(original: str, width: int) -> str:
    """The largest standard Commons thumbnail narrower than the original.

    Wikimedia throttles automated downloads of original files hard, and serves thumbnails only at standard
    widths (https://w.wiki/GHai); the original is used only when it is narrower than every standard width.
    """
    step = next((s for s in reversed(THUMB_STEPS) if s < width), None)
    match = re.match(r"(https://upload\.wikimedia\.org/wikipedia/commons)/(\w/\w\w)/([^/]+)$", original)
    if step is None or not match:
        return original
    root, shard, name = match.groups()
    return f"{root}/thumb/{shard}/{name}/{step}px-{name}"


def _fetch_bytes(url: str) -> bytes:
    """One picture, patiently: Wikimedia answers bursts with 429 and a Retry-After."""
    for attempt in range(6):
        resp = requests.get(url, headers={"User-Agent": USER_AGENT}, timeout=120)
        if resp.status_code == 200:
            return resp.content
        if resp.status_code not in (429, 500, 502, 503, 504) or attempt == 5:
            resp.raise_for_status()
        after = resp.headers.get("Retry-After", "")
        wait = min(float(after) if after.isdigit() else 0.0, 90.0) or 5.0 * 2**attempt
        log.info("picture download %s returned %d; waiting %.0fs", url.rsplit("/", 1)[-1][:60], resp.status_code, wait)
        time.sleep(wait)
    raise RuntimeError(f"{url} kept failing")


def download(chosen: list[dict | int], folder: Path) -> list[dict | int]:
    """Save every chosen picture under folder as picNN.jpg and record its relative path in "path".

    A picture that still can't be fetched is replaced by a repeat of the previous picture; fewer than 3
    distinct pictures left is an error.
    """
    from PIL import Image, ImageOps

    folder.mkdir(parents=True, exist_ok=True)
    result: list[dict | int] = []
    for i, pic in enumerate(chosen):
        if isinstance(pic, int):
            result.append(pic if isinstance(result[pic - 1], dict) else result[pic - 1])
            continue
        target = folder / f"pic{i:02d}.jpg"
        try:
            image = ImageOps.exif_transpose(Image.open(io.BytesIO(_fetch_bytes(pic["url"]))))
            if max(image.size) < 600:
                raise ValueError(f"only {image.width}x{image.height}")
            image.convert("RGB").save(target, quality=95)
        except (requests.RequestException, RuntimeError, OSError, ValueError) as err:
            log.warning("picture %d (%s) failed: %s", i + 1, pic["url"], err)
            earlier = next((n for n in range(i, 0, -1) if isinstance(result[n - 1], dict)), None)
            if earlier is None:
                raise LookupError(f"first picture failed: {err}") from err
            result.append(earlier)
            continue
        result.append({**pic, "path": f"{folder.name}/{target.name}"})
        time.sleep(1.5)
    distinct = sum(isinstance(p, dict) for p in result)
    if distinct < 3:
        raise LookupError(f"only {distinct} distinct pictures could be downloaded")
    return result


def commons_candidates(query: str) -> list[dict]:
    data = _get(COMMONS_API, {
        "action": "query", "format": "json", "generator": "search", "gsrsearch": f"{query} filetype:bitmap",
        "gsrnamespace": 6, "gsrlimit": 40, "prop": "imageinfo", "iiprop": "url|size|mime|extmetadata",
    })
    pages = sorted((data.get("query") or {}).get("pages", {}).values(), key=lambda p: p.get("index", 0))
    terms = [t.lower() for t in re.findall(r"[A-Za-z]{3,}", query)
             if t.lower() not in {"painting", "folio", "the", "and", "with", "from", "scene"}]
    found = []
    for page in pages:
        info = (page.get("imageinfo") or [{}])[0]
        meta = info.get("extmetadata") or {}
        title = page.get("title", "").removeprefix("File:")
        license_name = _meta(meta, "LicenseShortName")
        text = " ".join([title, _meta(meta, "Categories"), _meta(meta, "ObjectName"),
                         _meta(meta, "ImageDescription")[:600]])
        if info.get("mime") not in ("image/jpeg", "image/png"):
            continue
        if max(info.get("width", 0), info.get("height", 0)) < MIN_SIDE or not LICENSE_OK.match(license_name):
            continue
        if not PAINTING.search(text) or REJECT.search(text):
            continue
        year = _year(_meta(meta, "DateTimeOriginal"))
        if year and year > 1950:
            continue
        hits = sum(t in text.lower() for t in terms)
        if terms and not hits:
            continue
        found.append({
            "url": thumb_url(info.get("url", ""), int(info.get("width") or 0)),
            "credit": {"source": "Wikimedia Commons", "title": re.sub(r"\.(jpe?g|png)$", "", title, flags=re.I),
                       "credit": _meta(meta, "Artist")[:160] or "Unknown artist", "license": license_name,
                       "url": info.get("descriptionurl")},
            "key": f"commons:{title}", "hits": hits,
            "portrait": info.get("height", 0) >= info.get("width", 1),
        })
    found.sort(key=lambda c: (-c["hits"], not c["portrait"]))
    return found


def cleveland_candidates(query: str) -> list[dict]:
    data = _get(CLEVELAND_API, {"q": query, "has_image": 1, "cc0": 1, "limit": 20, "department": "Indian and Southeast Asian Art"})
    found = []
    for work in data.get("data") or []:
        image = ((work.get("images") or {}).get("web") or (work.get("images") or {}).get("print") or {})
        if not image.get("url") or max(int(image.get("width") or 0), int(image.get("height") or 0)) < 900:
            continue
        text = " ".join(str(work.get(k) or "") for k in ("title", "type", "technique", "culture"))
        if REJECT.search(str(work.get("type") or "")) or not re.search(r"painting|drawing|print|manuscript|folio", text, re.I):
            continue
        culture = work.get("culture")
        culture = culture[0] if isinstance(culture, list) and culture else culture
        creator = (work.get("creators") or [{}])[0].get("description")
        found.append({
            "url": image["url"],
            "credit": {"source": "Cleveland Museum of Art", "title": work.get("title") or "Untitled",
                       "credit": creator or culture or "Unknown artist", "license": "CC0", "url": work.get("url")},
            "key": f"cleveland:{work.get('id')}", "hits": 1, "portrait": int(image.get("height") or 0) >= int(image.get("width") or 1),
        })
    return found


def pick(queries: list[str], used: set[str]) -> dict | None:
    """The best unused painting for the first query that finds one."""
    for query in queries:
        for search in (commons_candidates, cleveland_candidates):
            try:
                candidates = search(query)
            except Exception as err:  # one source being down must not stop the Short
                log.warning("%s failed for %r: %s", search.__name__, query, err)
                continue
            for cand in candidates:
                if cand["key"] not in used:
                    used.add(cand["key"])
                    return cand
    return None


def choose(beats: list[dict], work: str) -> list[dict | int]:
    """For each beat: a picture dict, or the 1-based number of an earlier beat whose picture it reuses.

    The loop line (last beat) always reuses beat 1's picture, so the replay is seamless.
    """
    used: set[str] = set()
    chosen: list[dict | int] = []
    fallbacks = WORK_FALLBACKS.get(work, ["Hindu mythology painting"])
    for i, beat in enumerate(beats):
        if i == len(beats) - 1 and i > 0 and isinstance(chosen[0], dict):
            chosen.append(1)
            continue
        query = beat.get("visual_query") or ""
        words = query.split()
        queries = [f"{query} painting", query] + ([" ".join(words[:1]) + " painting"] if len(words) > 1 else [])
        found = pick(queries, used)
        if found is None and i > 0:
            # Repeat the previous distinct picture rather than reach for a weak match.
            earlier = next(n for n in range(i, 0, -1) if isinstance(chosen[n - 1], dict))
            chosen.append(earlier)
            continue
        if found is None:
            found = pick(fallbacks, used)
        if found is None:
            raise LookupError(f"no public-domain painting found for beat {i + 1} ({query!r})")
        chosen.append(found)
    distinct = sum(isinstance(c, dict) for c in chosen)
    if distinct < 3:
        for extra in fallbacks:
            if distinct >= 3:
                break
            found = pick([extra], used)
            if found:
                # Give the extra picture to the longest run of reused beats.
                for n in range(1, len(chosen) - 1):
                    if isinstance(chosen[n], int):
                        chosen[n] = found
                        distinct += 1
                        break
    if distinct < 3:
        raise LookupError(f"only {distinct} distinct public-domain paintings found")
    return chosen
